### ISSUE TITLE
Deleting a global option persists for all instances

### ISSUE THREAD

**Issue by mercyaj** [ava/use-http#250]
Possibly related to  #135 

**Describe the bug**
When deleting/overwriting a global option in one instance of useFetch, the global options are then permanently modified across all instances.

Following the example in the README:

```
 // let's say for this request, you don't want the `Accept` header at all
  const { loading, error, data: todos } = useFetch(globalOptions => {
    delete globalOptions.headers.Accept
    return {
      data: [],
      ...globalOptions
    }
  }, []) // onMount
```

This line:
``delete globalOptions.headers.Accept``

Will delete the Accept header for all useFetch instances across an app.

**⚠️ Make a Codesandbox ⚠️**
https://codesandbox.io/embed/goofy-bird-yhon5?fontsize=14&hidenavigation=1&theme=dark

**To Reproduce**
1. Go to Login page
2. Click on "Login" button
3. Open the console - the Todo useFetch options do not have the interceptors.request property that is defined in the global options passed to the Provider.

**Expected behavior**
I would expect that modifying the global options in an instance of useFetch would create a local copy and would not affect the global options in any other instances.

**Comment by alex-cory** [comment]
Thank you! Will get to this asap. If you get to it before me/would like to contribute, [here's how](https://github.com/ava/use-http/blob/master/.github/contributing.md).

**Comment by alex-cory** [comment]
This should be fixed as of `v1.0.8`

**Comment by mercyaj** [comment]
@alex-cory unfortunately I'm still experiencing issues with this in `v1.0.8`. I've updated [the Codesandbox](https://codesandbox.io/s/gifted-night-pkq7p) to show the new issue. I believe the problem lies [here](https://github.com/ava/use-http/blob/90778f3245a9615f35bbcb959515269153687a1d/src/useFetchArgs.ts#L44). The fix merged above works for headers but not interceptors.

**Comment by alex-cory** [comment]
Apologies for missing that. Will get it merged today.

**Comment by alex-cory** [comment]
should be fixed in `v1.0.10`
